apiVersion: v1
kind: Service
metadata:
  name: js-calc-frontend
  namespace: dapr-calc
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: js-calc-frontend
  type: LoadBalancer
  externalTrafficPolicy: Local