apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: set-proxy
  labels:
    app: set-proxy
spec:
  selector:
    matchLabels:
      name: set-proxy
  template:
    metadata:
      labels:
        name: set-proxy
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
        - name: set-proxy
          securityContext:
            privileged: true
          image: busybox
          imagePullPolicy: Always
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command: [ "sh", "-c"]
          args:
          - while true; do
              echo "proxy contents"
              cat /host/etc/environment           
              if grep -q SomeString "/host/etc/environment"; then
                echo -e "http_proxy=http://192.168.43.100:3128/\nhttps_proxy=https://192.168.43.100:3128/" | sudo tee -a /host/etc/environment
              fi
              sleep 100;
            done;
          resources:
            requests:
              cpu: 5m
              memory: 50Mi
          volumeMounts:
            - name: host-etc
              mountPath: /host/etc
              readOnly: true
      volumes:
      - name: host-etc
        hostPath:
          path: /etc
          type: Directory