apiVersion: v1 
kind: Service 
metadata: 
  labels: 
    app: bookbuyer 
  name: bookbuyer 
  namespace: bookbuyer 
spec: 
  ports: 
  - name: dummy-unused-port 
    port: 9999 
    protocol: TCP 
    targetPort: 9999 
  selector: 
    app: bookbuyer 