apiVersion: v1 
kind: Service 
metadata: 
  name: bookstore 
  namespace: bookstore 
spec: 
  ports: 
  - port: 80 
    name: bookstore-port 
  selector: 
    app: bookstore-v1 
---
apiVersion: v1 
kind: Service 
metadata: 
  name: bookstore-v1 
  namespace: bookstore 
spec: 
  ports: 
  - port: 80 
    name: bookstore-port 
  selector: 
    app: bookstore-v1 
---
apiVersion: v1 
kind: Service 
metadata: 
  name: bookstore-v2 
  namespace: bookstore 
spec: 
  ports: 
  - port: 80 
    name: bookstore-port 
  selector: 
    app: bookstore-v2 