apiVersion: specs.smi-spec.io/v1alpha3 
kind: HTTPRouteGroup 
metadata: 
  name: bookstore-service-routes 
  namespace: bookstore 
spec: 
  matches: 
  - name: books-bought 
    pathRegex: /books-bought 
    methods: 
    - GET 
    headers: 
    - "user-agent": ".*-http-client/*.*" 
    - "client-app": "bookbuyer" 
  - name: buy-a-book 
    pathRegex: ".*a-book.*new" 
    methods: 
    - GET 
  - name: update-books-bought 
    pathRegex: /update-books-bought 
    methods: 
    - POST 